services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: sunbunnies_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_DB: sunbunnies_prod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sunbunnies_app -d sunbunnies_prod"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:3.9.0
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: sunbunnies_app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_DB: sunbunnies_prod
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_SSL_MODE: disable
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: user-events
      KAFKA_CONSUMER_GROUP_ID: projector
      KAFKA_CONSUMER_START_OFFSET: first
      GRPC_TARGET_ADDR: ml:50051
      GRPC_TIMEOUT: 30s
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  ml:
    build: ./ml
    environment:
      auth_key: ${GIGACHAT_KEY}
      scope: GIGACHAT_API_PERS
      certificate: src/cert.cer
      model: GigaChat-3-Lightning
      timeout: "16"
      max_retries: "3"
    depends_on:
      - backend

volumes:
  pgdata: