// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: quiz.proto

package quiz_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionRequest) Reset() {
	*x = GenerateQuestionRequest{}
	mi := &file_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionRequest) ProtoMessage() {}

func (x *GenerateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQuestionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionResponse) Reset() {
	*x = GenerateQuestionResponse{}
	mi := &file_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionResponse) ProtoMessage() {}

func (x *GenerateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_quiz_proto protoreflect.FileDescriptor

const file_quiz_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"quiz.proto\x12\x12sunbunnies.quiz.v1\"3\n" +
	"\x17GenerateQuestionRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x18GenerateQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer2|\n" +
	"\vQuizService\x12m\n" +
	"\x10GenerateQuestion\x12+.sunbunnies.quiz.v1.GenerateQuestionRequest\x1a,.sunbunnies.quiz.v1.GenerateQuestionResponseBJZHgithub.com/CodesForge/SunBunniesHackathon2026Project/pkg/quiz/v1;quiz_v1b\x06proto3"

var (
	file_quiz_proto_rawDescOnce sync.Once
	file_quiz_proto_rawDescData []byte
)

func file_quiz_proto_rawDescGZIP() []byte {
	file_quiz_proto_rawDescOnce.Do(func() {
		file_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quiz_proto_rawDesc), len(file_quiz_proto_rawDesc)))
	})
	return file_quiz_proto_rawDescData
}

var file_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quiz_proto_goTypes = []any{
	(*GenerateQuestionRequest)(nil),  // 0: sunbunnies.quiz.v1.GenerateQuestionRequest
	(*GenerateQuestionResponse)(nil), // 1: sunbunnies.quiz.v1.GenerateQuestionResponse
}
var file_quiz_proto_depIdxs = []int32{
	0, // 0: sunbunnies.quiz.v1.QuizService.GenerateQuestion:input_type -> sunbunnies.quiz.v1.GenerateQuestionRequest
	1, // 1: sunbunnies.quiz.v1.QuizService.GenerateQuestion:output_type -> sunbunnies.quiz.v1.GenerateQuestionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quiz_proto_init() }
func file_quiz_proto_init() {
	if File_quiz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quiz_proto_rawDesc), len(file_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quiz_proto_goTypes,
		DependencyIndexes: file_quiz_proto_depIdxs,
		MessageInfos:      file_quiz_proto_msgTypes,
	}.Build()
	File_quiz_proto = out.File
	file_quiz_proto_goTypes = nil
	file_quiz_proto_depIdxs = nil
}
