apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s.fullname" . }}-migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/goose"]
          args:
            - -dir
            - /app/migrations
            - postgres
            - "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=$(POSTGRES_SSL_MODE)"
            - up
          envFrom:
            - secretRef:
                name: {{ include "k8s.fullname" . }}-secret
            - configMapRef:
                name: {{ include "k8s.fullname" . }}-config