apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-ml-secret
type: Opaque
stringData:
  auth_key: {{ .Values.ml.secret.authKey | quote }}
  scope: {{ .Values.ml.secret.scope | quote }}
  certificate: {{ .Values.ml.secret.certificate | quote }}
  model: {{ .Values.ml.secret.model | quote }}
  timeout: {{ .Values.ml.secret.timeout | quote }}
  max_retries: {{ .Values.ml.secret.maxRetries | quote }}

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
