apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}-ml-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ml.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "k8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ml