apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-secret
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
type: Opaque
stringData:
  # POSTGRES ENV
  POSTGRES_USER: {{ .Values.secret.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.database.password | quote }}
  POSTGRES_DB: {{ .Values.secret.database.db | quote }}

  # KAFKA ENV
  KAFKA_CONSUMER_GROUP_ID: {{ .Values.secret.kafka.groupId | quote }}

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
